Metrics/BlockLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Layout/LineLength:
  Max: 400

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/FormatString:
  Enabled: false

